spring:
  application:
    name: BOOKINGS-SERVICE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ilu-realm
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/db
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092 
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

booking:
  kafka:
    topic: bookings.events

resilience4j:
  circuitbreaker:
    instances:
      MOVIES-SERVICE:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

  retry:
    instances:
      MOVIES-SERVICE:
        maxAttempts: 3
        waitDuration: 1s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops, bus-refresh
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true