spring:
  application:
    name: BOOKINGS-SERVICE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ilu-realm
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/db
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer:   org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      spring.json.add.type.headers: false

booking:
  kafka:
    topic-bookings: bookings.events
    topic-movie-requests: movies.request
    topic-movie-responses: movies.response

resilience4j:
  circuitbreaker:
    instances:
      MOVIES-SERVICE:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

  retry:
    instances:
      MOVIES-SERVICE:
        maxAttempts: 3
        waitDuration: 1s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops, bus-refresh
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    org.springframework.boot.autoconfigure.web: DEBUG
    org.springframework.security.access: DEBUG 
    org.springframework.data.transaction: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.kafka.transaction: DEBUG